import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Lightbulb, Sparkles, Target } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { interviewService } from '../services/interviewService';
import { Alert, Loading, ScoreBar } from '../components/common/UI';
import { getErrorMessage } from '../services/api';

const scoreFields = [['Overall', 'overall_score'], ['Technical knowledge', 'technical_score'], ['Communication', 'communication_score'], ['Relevance', 'relevance_score'], ['Clarity', 'clarity_score'], ['Completeness', 'completeness_score'], ['Problem solving', 'problem_solving_score']];
export default function Feedback() {
  const { id } = useParams();
  const [analysis, setAnalysis] = useState(null);
  const [interview, setInterview] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { Promise.all([interviewService.analysis(id), interviewService.get(id)]).then(([result, item]) => { setAnalysis(result); setInterview(item); }).catch((e) => setError(getErrorMessage(e))).finally(() => setLoading(false)); }, [id]);
  if (loading) return <Loading label="Loading detailed feedback…" />;
  if (error) return <Alert>{error}</Alert>;
  return <div><Link to={`/interview/${id}/result`} className="back-link"><ArrowLeft size={15} /> Back to results</Link><div className="page-heading"><div><div className="section-kicker">YOUR ANSWERS, REVIEWED</div><h1>Detailed feedback</h1><p>{interview?.job_role} <span>·</span> {interview?.interview_type} interview</p></div></div><div className="feedback-intro card"><Sparkles size={16} /><p>Scores reflect AI-generated observations about the text of your answer. Treat them as suggestions to support your own practice.</p></div><div className="feedback-stack">{analysis?.questions?.map((item, i) => <article className="card answer-review" key={`${item.question}-${i}`}><div className="answer-review-head"><span className="question-index">QUESTION {String(i + 1).padStart(2, '0')}</span><span className="badge">{Math.round(item.analysis.overall_score)}/100</span></div><h2>{item.question}</h2><div className="submitted-answer"><span className="answer-label">YOUR ANSWER</span><p>{item.answer}</p></div><div className="answer-feedback-grid"><div><div className="feedback-list-heading"><span className="feedback-icon good"><Check size={14} /></span><h3>What worked well</h3></div>{item.analysis.strengths.map((text) => <p className="feedback-bullet" key={text}>{text}</p>)}</div><div><div className="feedback-list-heading"><span className="feedback-icon next"><Target size={14} /></span><h3>What to try next</h3></div>{item.analysis.weaknesses.map((text) => <p className="feedback-bullet" key={text}>{text}</p>)}</div></div><div className="answer-scores"><div className="feedback-list-heading"><span className="feedback-icon score"><Sparkles size={14} /></span><h3>Score breakdown</h3></div><div className="answer-scores-grid">{scoreFields.map(([label, key]) => <ScoreBar key={key} label={label} value={item.analysis[key]} />)}</div></div><div className="suggested-answer"><div className="feedback-list-heading"><span className="feedback-icon tip"><Lightbulb size={14} /></span><h3>Example direction</h3></div><p>{item.analysis.suggested_answer}</p></div>{item.analysis.missing_topics?.length > 0 && <div className="missing-topics"><strong>Topics you could mention</strong><div>{item.analysis.missing_topics.map((topic) => <span className="badge" key={topic}>{topic}</span>)}</div></div>}<div className="tip-banner"><Lightbulb size={15} /><span><strong>One tip:</strong> {item.analysis.improvement_tip}</span></div></article>)}</div>{!analysis?.questions?.length && <div className="card empty-state"><h3>No answer feedback yet</h3><p>Submit answers in the interview session to see feedback.</p></div>}<div className="feedback-footer"><Link to="/interview/new" className="button button-primary">Practice another interview <ArrowRight size={15} /></Link></div></div>;
}
