import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Search, SlidersHorizontal, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { interviewService } from '../services/interviewService';
import { Alert, EmptyState, Loading } from '../components/common/UI';
import { getErrorMessage } from '../services/api';

export default function History() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All sessions');
  useEffect(() => { interviewService.list().then(setItems).catch((e) => setError(getErrorMessage(e))).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => items.filter((item) => `${item.job_role} ${item.interview_type} ${item.difficulty}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All sessions' || (status === 'Completed' ? item.status === 'completed' : item.status !== 'completed'))), [items, query, status]);
  const remove = async (item) => { if (!window.confirm(`Delete your ${item.job_role} interview? This cannot be undone.`)) return; try { await interviewService.remove(item.id); setItems((current) => current.filter((i) => i.id !== item.id)); } catch (e) { setError(getErrorMessage(e)); } };
  if (loading) return <Loading label="Loading your history…" />;
  return <div><div className="page-heading"><div><div className="section-kicker">YOUR PRACTICE JOURNEY</div><h1>Interview history</h1><p>Every session is another step forward.</p></div><Link to="/interview/new" className="button button-primary">Start interview <ArrowRight size={15} /></Link></div><Alert>{error}</Alert><section className="card history-card"><div className="history-toolbar"><div className="search-box"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search roles or interview types…" aria-label="Search interview history" /></div><div className="filter-select"><SlidersHorizontal size={15} /><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Filter interviews"><option>All sessions</option><option>Completed</option><option>In progress</option></select></div><span className="history-count">{filtered.length} session{filtered.length === 1 ? '' : 's'}</span></div>{filtered.length ? <div className="table-wrap"><table className="data-table history-table"><thead><tr><th>Date</th><th>Job role</th><th>Type</th><th>Difficulty</th><th>Score</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</td><td><strong>{item.job_role}</strong></td><td>{item.interview_type}</td><td><span className="badge">{item.difficulty}</span></td><td>{item.overall_score == null ? '—' : <strong>{Math.round(item.overall_score)}<small className="score-total">/100</small></strong>}</td><td><span className={`badge status-badge ${item.status}`}>{item.status === 'completed' ? 'Completed' : item.status === 'in_progress' ? 'In progress' : 'Ready'}</span></td><td><div className="history-actions"><Link className="table-action" to={item.status === 'completed' ? `/interview/${item.id}/result` : `/interview/${item.id}`}>{item.status === 'completed' ? 'Results' : 'Continue'} <ArrowRight size={13} /></Link><button className="delete-icon" onClick={() => remove(item)} aria-label={`Delete ${item.job_role} interview`}><Trash2 size={14} /></button></div></td></tr>)}</tbody></table></div> : <EmptyState title="Nothing here just yet" description={query || status !== 'All sessions' ? 'Try a different search or filter.' : 'Your practice history will live here.'} action={query || status !== 'All sessions' ? null : <Link className="button button-primary" to="/interview/new">Start your first interview</Link>} />}</section><p className="assessment-note">Your interview answers are stored privately in your account. You can delete sessions at any time.</p></div>;
}
