import { ArrowDown, ArrowRight, AudioLines, BrainCircuit, ChartNoAxesCombined, Check, ChevronRight, CircleHelp, Code2, MessageSquareText, Sparkles, Target, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';

const features = [
  { icon: BrainCircuit, title: 'Questions that fit your goals', text: 'Practice role-specific questions shaped around your experience and interview style.' },
  { icon: MessageSquareText, title: 'Feedback you can use', text: 'Understand what landed well and where a clearer, more complete answer helps.' },
  { icon: Code2, title: 'Technical practice', text: 'Work through technical prompts with topic-aware guidance and structured scoring.' },
  { icon: AudioLines, title: 'Communication insights', text: 'Review clarity, relevance, structure, and the detail behind your answers.' },
  { icon: Target, title: 'Personal improvement plan', text: 'Get practical next steps tailored to your submitted answers.' },
  { icon: ChartNoAxesCombined, title: 'Progress at a glance', text: 'Keep your sessions in one place and see how your practice evolves.' },
];

export default function Landing() {
  return <div className="landing">
    <nav className="landing-nav container"><Link to="/" className="brand"><span className="brand-mark">✳</span><span>interviewly</span></Link><div className="landing-nav-links"><a href="#features">Features</a><a href="#how-it-works">How it works</a></div><div className="landing-auth"><Link to="/login" className="text-link">Log in</Link><Link to="/register" className="button button-primary button-small">Get started <ArrowRight size={15} /></Link></div></nav>
    <section className="hero container">
      <div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> YOUR NEXT INTERVIEW STARTS HERE</div><h1>Practice smarter.<br /><span>Interview better.</span></h1><p className="hero-subtitle">AI-powered interview practice and personalized feedback to help you show up with confidence.</p><div className="hero-actions"><Link to="/register" className="button button-primary button-large">Start interview <ArrowRight size={17} /></Link><Link to="/register" className="button button-white button-large"><Sparkles size={17} /> Try a demo</Link></div><div className="hero-proof"><div className="proof-avatars"><span>J</span><span>M</span><span>A</span><span>+</span></div><div><strong>Your practice space, always ready</strong><small>No AI key required to try demo mode</small></div></div></div>
      <div className="hero-visual" aria-label="Interview analysis preview"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-spark spark-a">✳</div><div className="hero-spark spark-b">✦</div><div className="mock-window"><div className="mock-top"><div className="mock-dots"><i /><i /><i /></div><span>YOUR SESSION</span><span className="live-tag"><i /> PRACTICE</span></div><div className="mock-body"><div className="mock-question"><span className="mock-q-label">QUESTION 02 <span>·</span> BEHAVIORAL</span><h3>Tell me about a time you solved a challenging problem.</h3><div className="answer-lines"><i /><i /><i /><i /></div><div className="mock-mic"><AudioLines size={19} /></div><small>Your answer is saved privately</small></div><div className="mock-score-card"><div className="score-ring"><span>86<small>/100</small></span></div><div className="score-note"><span className="label-cap">AI FEEDBACK</span><strong>Thoughtful response</strong><p>Clear structure, with a strong example.</p><div className="mini-tags"><span><Check size={11} /> Relevant</span><span><Zap size={11} /> Specific</span></div></div></div><div className="mock-progress"><span /><span /><span /><span /><span /></div></div></div><div className="floating-badge"><span className="floating-icon"><Sparkles size={15} /></span><div><strong>Small steps add up</strong><small>One answer at a time</small></div></div></div>
      <a className="scroll-cue" href="#features">Scroll to explore <ArrowDown size={14} /></a>
    </section>
    <section id="features" className="features-section"><div className="container"><div className="section-heading"><span className="section-kicker">A BETTER WAY TO PREPARE</span><h2>Make every practice count.</h2><p>Get thoughtful feedback that makes your next answer stronger.</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, text }, index) => <article key={title} className="feature-card"><div className={`feature-icon feature-icon-${index}`}><Icon size={20} strokeWidth={1.8} /></div><h3>{title}</h3><p>{text}</p><ChevronRight size={16} className="feature-arrow" /></article>)}</div></div></section>
    <section id="how-it-works" className="how-section"><div className="container how-grid"><div className="how-intro"><span className="section-kicker">SIMPLE BY DESIGN</span><h2>From first question to a better answer.</h2><p>A calm, focused space to practice at your own pace — with actionable guidance along the way.</p><Link to="/register" className="button button-dark">Start practicing <ArrowRight size={16} /></Link></div><div className="steps">{[{ n: '01', title: 'Choose your interview', text: 'Set your role, experience level, type and difficulty.' }, { n: '02', title: 'Answer questions', text: 'Take your time and respond in your own words.' }, { n: '03', title: 'Get thoughtful analysis', text: 'See strengths, opportunities and a suggested answer.' }, { n: '04', title: 'Build your confidence', text: 'Use your feedback to make the next practice count.' }].map((step) => <div className="step" key={step.n}><span className="step-number">{step.n}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></div>)}</div></div></section>
    <section className="cta-section container"><div className="cta-panel"><div className="cta-spark">✳</div><span className="section-kicker">YOUR NEXT STEP</span><h2>Ready to sharpen your interview skills?</h2><p>Start with one question. Leave with a clearer way forward.</p><Link to="/register" className="button button-primary button-large">Start practicing <ArrowRight size={17} /></Link></div></section>
    <footer className="landing-footer container"><Link to="/" className="brand"><span className="brand-mark">✳</span><span>interviewly</span></Link><p>Practice with purpose. Progress at your pace.</p><span>AI feedback is a coaching aid, not a hiring decision.</span></footer>
  </div>;
}
